programa = expLogica+
instrucao = (sp)* (declaracao/atribuicao/leia/escreva/se) (sp)*
declaracao = declaracaoConstante / declaracaoVariavel
declaracaoConstante = "CONSTANTE" sp+ identificadorCONSTANTE sp* "=" sp* expressao
declaracaoVariavel = ("DECLARE"/"DECLARA") sp+ identificadorVariavel sp* ("," sp* identificadorVariavel)* ":" sp* tipo
atribuicao = identificadorVariavel sp* "=" sp* expressao

leia = "LEIA" sp+ identificadorVariavel
escreva = "ESCREVA" sp+ (string/variavel)
se = "SE" sp* expLogica sp* "ENTÃO" instrucao "SENÃO" instrucao
/ "SE" sp* expLogica sp* "ENTÃO" instrucao


expressao= sp* fator expAdicao* sp*
expAdicao= ('+'/'-') sp* fator sp*
fator = primario expMultiplicacao* sp*
expMultiplicacao = ('*'/'/') sp* primario sp*
primario = (parenteses / numero / variavel / '-' primario) sp*
parenteses = '(' expressao ')' sp*
variavel = identificadorCONSTANTE / identificadorVariavel

expLogica = (expLogicaQuaternario)+
expLogicaQuaternario = expLogicaTerciario ("OU" expLogicaTerciario)*
expLogicaTerciario = expLogicaSecundario ("E" expLogicaSecundario)*
expLogicaSecundario = ("NÃO")? expLogicaPrimario
expLogicaPrimario = expressao opComparacao expressao / sp* "(" expLogica ")"
opComparacao = ">=" / "<=" / "==" / "!=" / "<" / ">"


numero = ("-")? digito+
identificadorCONSTANTE = ([A-Z]/"_")+
identificadorVariavel = ([a-z]/"_")+ ([a-z]/"_"/[A-Z]/[0-9])*
tipo = "NUMERO"/"TEXTO"


digito = [0-9]
sp = " " / "\t" / "\n"
string = aspas (!aspas .)* aspas
aspas = "\""
